import {esc} from './markdown.mjs';
import {availableLocales} from './reports.mjs';

export function makeLayout(ctx){
  const {cfg,i18n,site,author,social,locale,reportPath,pagePath}=ctx;
  const loc=cfg.locales[locale],t=i18n[locale]||i18n[cfg.default_locale];
  const prefix=loc.path?`/${loc.path}`:'';
  const abs=u=>/^https?:\/\//.test(String(u||''))?u:`${site}${u}`;
  const safe=u=>/^(https?:\/\/|mailto:|\/|#)/i.test(String(u||''))?esc(u):'#';
  const iso=v=>String(v||'').slice(0,10);
  const role=a=>typeof a?.role==='object'?(a.role[locale]||a.role[cfg.default_locale]||Object.values(a.role)[0]):(a?.role||'');
  const authors=i=>Array.isArray(i.authors)&&i.authors.length?i.authors:[author];
  const authorUrl=a=>`${prefix}/authors/${a.slug||author.slug}/`;
  const localized=(p)=>pagePath(locale,p);
  function brand(){return `<a class="brand" href="${localized('/index.html')}" aria-label="Marginal Thinking"><span class="brand-mark"><i></i></span><span class="brand-name"><strong>MARGINAL</strong><em>THINKING</em></span></a>`;}
  function languageSwitch(alternates={}){
    const links=Object.entries(cfg.locales).map(([code,c])=>{const target=alternates[code]||pagePath(code,'/index.html');const current=code===locale;return `<a href="${safe(target)}" hreflang="${esc(c.lang)}" lang="${esc(c.lang)}" title="${esc(c.name)}" aria-label="${esc(c.name)}"${current?' aria-current="true" class="active"':''}>${esc(c.label)}</a>`;}).join('');
    return `<div class="language-switch" role="navigation" aria-label="${esc(t.language_label||'Language')}">${links}</div>`;
  }
  function themeToggle(){
    const label=locale==='pt-BR'?'Alternar tema claro e escuro':'Toggle light and dark theme';
    return `<button class="theme-toggle" type="button" aria-label="${esc(label)}" title="${esc(label)}" aria-pressed="false"><span class="theme-icon theme-icon-moon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M20.5 14.1A8.7 8.7 0 0 1 9.9 3.5 8.7 8.7 0 1 0 20.5 14.1Z"/></svg></span><span class="theme-icon theme-icon-sun" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3.6"/><path d="M12 2.5v2M12 19.5v2M4.1 4.1l1.4 1.4M18.5 18.5l1.4 1.4M2.5 12h2M19.5 12h2M4.1 19.9l1.4-1.4M18.5 5.5l1.4-1.4"/></svg></span></button>`;
  }
  function nav(active='research',alternates={}){
    const a=(key,path,label)=>`<a href="${localized(path)}"${active===key?' class="active" aria-current="page"':''}>${esc(label)}</a>`;
    return `<header class="site-header"><div class="container header-row">${brand()}<nav class="nav" aria-label="${esc(t.nav.research)}">${a('home','/index.html',t.nav.home)}${a('research','/reports.html',t.nav.research)}${a('method','/methodology.html',t.nav.method)}${a('about','/about.html',t.nav.about)}</nav>${languageSwitch(alternates)}<div class="header-actions"><a class="header-report" href="${localized('/reports.html')}">${esc(t.nav.open)}</a>${themeToggle()}<button class="menu-toggle" type="button" aria-label="${esc(t.nav.menu)}" aria-controls="mobile-menu" aria-expanded="false"><span></span><span></span><span></span></button></div></div><div class="mobile-menu" id="mobile-menu"><div class="container mobile-menu-inner"><nav>${a('home','/index.html',t.nav.home)}${a('research','/reports.html',t.nav.research)}${a('method','/methodology.html',t.nav.method)}${a('about','/about.html',t.nav.about)}<div class="mobile-language">${languageSwitch(alternates)}</div></nav></div></div></header>`;
  }
  function footer(){return `<footer class="footer"><div class="container"><div class="footer-grid"><div class="footer-intro">${brand()}<p>${esc(t.footer.intro)}</p></div><div><div class="footer-title">${esc(t.footer.research)}</div><div class="footer-links"><a href="${localized('/reports.html')}">${esc(t.footer.archive)}</a><a href="${localized('/methodology.html')}">${esc(t.footer.method)}</a><a href="${localized('/feed.xml')}">RSS</a></div></div><div><div class="footer-title">${esc(t.footer.institutional)}</div><div class="footer-links"><a href="${localized('/about.html')}">${esc(t.footer.about)}</a><a href="${authorUrl(author)}">${esc(author.name)}</a><a href="mailto:${esc(author.email)}">${esc(t.footer.contact)}</a></div></div></div><div class="footer-bottom"><div class="footer-meta">${esc(cfg.institution)} · ${esc(t.country||'Brazil')}</div><div class="footer-meta">© 2026 ${esc(cfg.site_name)}</div></div></div></footer>`;}
  function alternatesHead(alternates={}){
    const links=Object.entries(alternates).map(([code,url])=>`<link rel="alternate" hreflang="${esc(cfg.locales[code]?.lang||code)}" href="${esc(abs(url))}">`).join('');
    const x=alternates[cfg.default_locale]||Object.values(alternates)[0];
    return links+(x?`<link rel="alternate" hreflang="x-default" href="${esc(abs(x))}">`:'');
  }
  function articleJson(i,view,canonical){const a=authors(i);return {'@type':'ScholarlyArticle','@id':`${abs(canonical)}#article`,headline:view.title,description:view.deck,datePublished:i.published_at||i.date,dateModified:i.updated_at||i.qa_reviewed_at||i.published_at||i.date,inLanguage:loc.lang,isAccessibleForFree:true,mainEntityOfPage:abs(canonical),url:abs(canonical),articleSection:t.kinds[i.kind]||i.kind,keywords:[...(view.tags||i.tags||[]),...(view.keywords||i.keywords||[])].join(', '),author:a.map(x=>({'@type':'Person',name:x.name,url:abs(authorUrl(x)),email:x.email||undefined})),publisher:{'@type':'Organization','@id':`${site}/#organization`,name:cfg.publisher,url:`${site}/`,logo:{'@type':'ImageObject',url:social}},image:social,license:'https://creativecommons.org/licenses/by/4.0/'};}
  function crumbs(i,view,canonical){return {'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:t.nav.home,item:abs(localized('/index.html'))},{'@type':'ListItem',position:2,name:t.nav.research,item:abs(localized('/reports.html'))},{'@type':'ListItem',position:3,name:view.title,item:abs(canonical)}]};}
  function reportHead(i,view,canonical,alternates={},robots='index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1'){
    const a=authors(i),modified=i.updated_at||i.qa_reviewed_at||i.published_at||i.date,graph=JSON.stringify({'@context':'https://schema.org','@graph':[articleJson(i,view,canonical),crumbs(i,view,canonical)]}).replace(/</g,'\\u003c');
    return `<meta name="robots" content="${esc(robots)}"><link rel="canonical" href="${esc(abs(canonical))}">${alternatesHead(alternates)}<link rel="alternate" type="application/rss+xml" title="Marginal Thinking — ${esc(t.nav.research)}" href="${esc(abs(localized('/feed.xml')))}"><meta property="og:type" content="article"><meta property="og:site_name" content="${esc(cfg.site_name)}"><meta property="og:locale" content="${esc(loc.og_locale)}"><meta property="og:title" content="${esc(view.title)}"><meta property="og:description" content="${esc(view.deck)}"><meta property="og:url" content="${esc(abs(canonical))}"><meta property="og:image" content="${esc(social)}"><meta property="article:published_time" content="${esc(i.published_at||i.date)}"><meta property="article:modified_time" content="${esc(modified)}">${(view.tags||i.tags||[]).slice(0,8).map(x=>`<meta property="article:tag" content="${esc(x)}">`).join('')}<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(view.title)}"><meta name="twitter:description" content="${esc(view.deck)}"><meta name="twitter:image" content="${esc(social)}"><meta name="citation_title" content="${esc(view.title)}">${a.map(x=>`<meta name="citation_author" content="${esc(x.name)}">`).join('')}<meta name="citation_publication_date" content="${iso(i.published_at||i.date)}"><meta name="citation_language" content="${esc(loc.lang)}"><meta name="citation_abstract" content="${esc(view.deck)}"><meta name="citation_fulltext_html_url" content="${esc(abs(canonical))}"><script type="application/ld+json">${graph}</script>`;
  }
  function baseHead(title,description,canonical,type='WebPage',alternates={},extra={}){const data=JSON.stringify({'@context':'https://schema.org','@type':type,url:abs(canonical),name:title,description,inLanguage:loc.lang,...extra}).replace(/</g,'\\u003c');return `<meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1"><link rel="canonical" href="${esc(abs(canonical))}">${alternatesHead(alternates)}<link rel="alternate" type="application/rss+xml" href="${esc(abs(localized('/feed.xml')))}" title="Marginal Thinking — ${esc(t.nav.research)}"><meta property="og:type" content="website"><meta property="og:site_name" content="${esc(cfg.site_name)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(abs(canonical))}"><meta property="og:image" content="${esc(social)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${esc(social)}"><script type="application/ld+json">${data}</script>`;}
  return{loc,t,prefix,abs,safe,role,authors,authorUrl,brand,languageSwitch,themeToggle,nav,footer,reportHead,baseHead,availableLocales};
}
