import {esc} from './markdown.mjs';

export function makeLayout(ctx){
 const {cfg,reports,kind,site,author,social}=ctx;
 const abs=u=>/^https?:\/\//.test(u)?u:`${site}${u}`;
 const safe=u=>/^(https?:\/\/|mailto:|\/|#)/i.test(String(u||''))?esc(u):'#';
 const iso=v=>String(v||'').slice(0,10);
 const authors=i=>Array.isArray(i.authors)&&i.authors.length?i.authors:[author];
 function brand(){return `<a class="brand" href="/index.html" aria-label="Marginal Thinking"><span class="brand-mark"><i></i></span><span class="brand-name"><strong>MARGINAL</strong><em>THINKING</em></span></a>`;}
 function nav(){return `<header class="site-header"><div class="container header-row">${brand()}<nav class="nav" aria-label="Navegação principal"><a href="/index.html">Início</a><a href="/reports.html" class="active">Pesquisas</a><a href="/methodology.html">Método</a><a href="/about.html">Sobre</a></nav><a class="header-report" href="/reports.html">Pesquisas</a><button class="menu-toggle" type="button" aria-label="Abrir menu" aria-controls="mobile-menu" aria-expanded="false"><span></span><span></span><span></span></button></div><div class="mobile-menu" id="mobile-menu"><div class="container mobile-menu-inner"><nav><a href="/index.html">Início</a><a href="/reports.html">Pesquisas</a><a href="/methodology.html">Método</a><a href="/about.html">Sobre</a></nav></div></div></header>`;}
 function footer(){return `<footer class="footer"><div class="container"><div class="footer-grid"><div class="footer-intro">${brand()}<p>Pesquisa independente sobre economia, política e sociedade.</p></div><div><div class="footer-title">Pesquisa</div><div class="footer-links"><a href="/reports.html">Arquivo</a><a href="/methodology.html">Método</a><a href="/feed.xml">RSS</a></div></div><div><div class="footer-title">Institucional</div><div class="footer-links"><a href="/about.html">Sobre</a><a href="/authors/${author.slug}/">${esc(author.name)}</a><a href="mailto:${esc(author.email)}">Contato</a></div></div></div><div class="footer-bottom"><div class="footer-meta">${esc(cfg.institution)} · Brasil</div><div class="footer-meta">© 2026 ${esc(cfg.site_name)}</div></div></div></footer>`;}
 function articleJson(i){const a=authors(i);return {'@type':'ScholarlyArticle','@id':`${abs(i.url)}#article`,headline:i.title,description:i.deck,datePublished:i.published_at||i.date,dateModified:i.updated_at||i.qa_reviewed_at||i.published_at||i.date,inLanguage:cfg.language,isAccessibleForFree:true,mainEntityOfPage:abs(i.url),url:abs(i.url),articleSection:kind[i.kind]||i.kind,keywords:[...(i.tags||[]),...(i.keywords||[])].join(', '),author:a.map(x=>({'@type':'Person',name:x.name,url:`${site}/authors/${x.slug||author.slug}/`,email:x.email||undefined})),publisher:{'@type':'Organization','@id':`${site}/#organization`,name:cfg.publisher,url:`${site}/`,logo:{'@type':'ImageObject',url:social}},image:social,license:'https://creativecommons.org/licenses/by/4.0/'};}
 function crumbs(i){return {'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Início',item:`${site}/`},{'@type':'ListItem',position:2,name:'Pesquisas',item:`${site}/reports.html`},{'@type':'ListItem',position:3,name:i.title,item:abs(i.url)}]};}
 function reportHead(i){const a=authors(i),modified=i.updated_at||i.qa_reviewed_at||i.published_at||i.date,graph=JSON.stringify({'@context':'https://schema.org','@graph':[articleJson(i),crumbs(i)]}).replace(/</g,'\\u003c');return `<meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"><link rel="canonical" href="${esc(abs(i.url))}"><link rel="alternate" type="application/rss+xml" title="Marginal Thinking — Pesquisas" href="${site}/feed.xml"><meta property="og:type" content="article"><meta property="og:site_name" content="${esc(cfg.site_name)}"><meta property="og:locale" content="pt_BR"><meta property="og:title" content="${esc(i.title)}"><meta property="og:description" content="${esc(i.deck)}"><meta property="og:url" content="${esc(abs(i.url))}"><meta property="og:image" content="${esc(social)}"><meta property="article:published_time" content="${esc(i.published_at||i.date)}"><meta property="article:modified_time" content="${esc(modified)}">${(i.tags||[]).slice(0,8).map(t=>`<meta property="article:tag" content="${esc(t)}">`).join('')}<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(i.title)}"><meta name="twitter:description" content="${esc(i.deck)}"><meta name="twitter:image" content="${esc(social)}"><meta name="citation_title" content="${esc(i.title)}">${a.map(x=>`<meta name="citation_author" content="${esc(x.name)}">`).join('')}<meta name="citation_publication_date" content="${iso(i.published_at||i.date)}"><meta name="citation_language" content="pt-BR"><meta name="citation_abstract" content="${esc(i.deck)}"><meta name="citation_fulltext_html_url" content="${esc(abs(i.url))}"><script type="application/ld+json">${graph}</script>`;}
 function baseHead(title,description,canonical,type='WebPage',extra={}){const data=JSON.stringify({'@context':'https://schema.org','@type':type,url:canonical,name:title,description,...extra}).replace(/</g,'\\u003c');return `<meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1"><link rel="canonical" href="${esc(canonical)}"><link rel="alternate" type="application/rss+xml" href="${site}/feed.xml" title="Marginal Thinking — Pesquisas"><meta property="og:type" content="website"><meta property="og:site_name" content="${esc(cfg.site_name)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(canonical)}"><meta property="og:image" content="${esc(social)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${esc(social)}"><script type="application/ld+json">${data}</script>`;}
 return{abs,safe,authors,brand,nav,footer,reportHead,baseHead};
}
