import fs from 'node:fs';
import path from 'node:path';
import {esc, renderMarkdown} from './markdown.mjs';
import {reportView, availableLocales} from './reports.mjs';

export const localizedPath=(cfg,locale,p)=>`${cfg.locales[locale]?.path?`/${cfg.locales[locale].path}`:''}${p}`;
export const label=(value,locale,fallback='')=>value?.[locale]||value?.en||fallback;
export const displayDate=(value,locale)=>value?new Intl.DateTimeFormat(locale,{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(`${String(value).slice(0,10)}T12:00:00Z`)):'';
export function countryLabel(country,locale){try{return new Intl.DisplayNames([locale],{type:'region'}).of(country.code)||country.slug;}catch{return country.slug;}}
export function researchCatalog({root,cfg,i18n,taxonomy,reports,locale,dependency,atlas}){
  return reports.filter(r=>availableLocales(r).includes(locale)).map(r=>{
    const v=reportView(r,locale),md=fs.readFileSync(path.join(root,v.markdown_url),'utf8');
    const words=md.replace(/```[\s\S]*?```/g,' ').replace(/\[[^\]]*\]\([^)]*\)/g,' ').split(/\s+/).filter(Boolean).length;
    const links=[];
    for(const e of dependency.edges||[])if(e.research_ids?.includes(r.id))links.push({label:`${label(dependency.nodes.find(n=>n.id===e.from)?.label,locale,e.from)} → ${label(dependency.nodes.find(n=>n.id===e.to)?.label,locale,e.to)}`,url:localizedPath(cfg,locale,`/dependencies/#relation-${e.id}`)});
    for(const e of atlas.entries||[])if(e.related_research_ids?.includes(r.id))links.push({label:label(e.feature,locale,e.id),url:localizedPath(cfg,locale,`/opportunities/#entry-${e.id}`)});
    return {id:r.id,date:r.date,updated:r.updated_at||r.qa_reviewed_at||r.date,title:v.title,deck:v.deck||'',url:localizedPath(cfg,locale,r.url),markdown:v.markdown_url,minutes:Math.max(1,Math.ceil(words/220)),kind:r.kind,kindLabel:i18n[locale].kinds[r.kind]||r.kind,program:r.program,programLabel:label(taxonomy.programs[r.program],locale,r.program),topics:(r.topics||[]).map(id=>({id,label:label(taxonomy.topics[id],locale,id)})),countries:(r.geography?.countries||[]).map(c=>({id:c.slug,label:countryLabel(c,locale)})),regime:v.regime||'',risk:v.key_risk||'',watch:v.watch||[],connections:links,keywords:[...(v.tags||[]),...(v.keywords||[])].join(' ')};
  });
}
export function saveButton(item,locale){return `<button type="button" class="research-save" data-save-research="${esc(item.id)}" data-research-title="${esc(item.title)}" aria-pressed="false" hidden><svg viewBox="0 0 20 20" aria-hidden="true"><path d="M5 3h10v14l-5-3-5 3Z"/></svg><span>${locale==='pt-BR'?'Salvar':'Save'}</span></button>`;}
export function researchTile(item,locale){return `<article class="editorial-card"><div class="editorial-meta"><span>${esc(item.kindLabel)}</span><time datetime="${esc(item.date)}">${esc(displayDate(item.date,locale))}</time></div><h3><a href="${esc(item.url)}">${esc(item.title)}</a></h3><p>${esc(item.deck)}</p><div class="editorial-actions"><a href="${esc(item.url)}">${locale==='pt-BR'?'Ler pesquisa':'Read research'} <span aria-hidden="true">↗</span></a><span class="reading-time">${item.minutes} min</span>${saveButton(item,locale)}</div></article>`;}

function evidence(item,locale,root){
  const pt=locale==='pt-BR',md=fs.readFileSync(path.join(root,item.markdown),'utf8'),match=/```chart\s*\n[\s\S]*?\n```/.exec(md);
  if(!match)return `<div class="home-evidence"><span class="product-kicker">${pt?'O QUE ACOMPANHAR':'WHAT TO WATCH'}</span><ul>${item.watch.slice(0,3).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><a href="${esc(item.url)}">${pt?'Entender a análise':'Explore the analysis'} ↗</a></div>`;
  // Keep the author's immediate qualification, including non-additivity and periods.
  const following=md.slice(match.index+match[0].length).trimStart().split(/\n\s*\n/)[0]||'';
  const note=!/^(#|```|\|)/.test(following)?renderMarkdown(following,{locale}).html:'';
  return `<div class="home-evidence"><div class="editorial-meta"><span>${pt?'EVIDÊNCIA DA EDIÇÃO':'FROM THE RESEARCH'}</span><time datetime="${esc(item.date)}">${esc(displayDate(item.date,locale))}</time></div>${renderMarkdown(match[0],{locale}).html}<div class="evidence-context">${note}<a href="${esc(item.url)}">${pt?'Contexto, período e fontes na pesquisa':'Context, period and sources in the research'} ↗</a></div></div>`;
}
function networkPreview(dependency,locale){
  const nodes=dependency.nodes.filter(n=>n.home_preview).slice(0,6),ids=new Set(nodes.map(n=>n.id));
  const positions=new Map(nodes.map((n,i)=>[n.id,{x:15+(i%3)*155,y:22+Math.floor(i/3)*95}]));
  const edges=dependency.edges.filter(e=>ids.has(e.from)&&ids.has(e.to));
  const paths=edges.map(e=>{const a=positions.get(e.from),b=positions.get(e.to);return `<path d="M${a.x+65} ${a.y+20} Q${(a.x+b.x)/2+65} ${(a.y+b.y)/2-5} ${b.x+65} ${b.y+20}"/>`;}).join('');
  return `<div class="tool-network-preview" aria-hidden="true"><svg viewBox="0 0 470 165">${paths}${nodes.map(n=>{const p=positions.get(n.id);return `<rect x="${p.x}" y="${p.y}" width="130" height="40" rx="3"/><circle cx="${p.x+8}" cy="${p.y+20}" r="3"/>`;}).join('')}</svg><div>${nodes.map(n=>`<span>${esc(label(n.label,locale))}</span>`).join('')}</div></div>`;
}
export function homeContent(ctx){
  const {root,cfg,taxonomy,reports,locale,dependency,atlas,i18n}=ctx,pt=locale==='pt-BR',p=s=>localizedPath(cfg,locale,s),items=researchCatalog(ctx),lead=items[0];
  const recent=[],kinds=new Set([lead?.kind]);
  for(const item of items.slice(1))if(!kinds.has(item.kind)){recent.push(item);kinds.add(item.kind);if(recent.length===3)break;}
  for(const item of items.slice(1))if(recent.length<3&&!recent.includes(item))recent.push(item);
  const topicCounts=new Map(),countries=new Map();
  for(const item of items){for(const x of item.topics){const prev=topicCounts.get(x.id);topicCounts.set(x.id,{...x,count:(prev?.count||0)+1});}for(const x of item.countries){const prev=countries.get(x.id);countries.set(x.id,{...x,count:(prev?.count||0)+1});}}
  const topics=[...topicCounts.values()].sort((a,b)=>b.count-a.count||a.id.localeCompare(b.id)).slice(0,6);
  const places=[...countries.values()].sort((a,b)=>b.count-a.count||a.id.localeCompare(b.id)).slice(0,6);
  const stateLabels=pt?['Ineficiência impeditiva','Ineficiência explorável','Eficiência impeditiva','Eficiência aproveitável']:['Blocking inefficiency','Exploitable inefficiency','Blocking efficiency','Leverageable efficiency'];
  const states=['blocking_inefficiency','exploitable_inefficiency','blocking_efficiency','leverageable_efficiency'];
  return `<main id="main-content" class="product-home">
    <section class="home-opening container"><div><div class="product-kicker">${pt?'ECONOMIA · POLÍTICA · SOCIEDADE':'ECONOMICS · POLITICS · SOCIETY'}</div><h1>${pt?'Entender o presente. Investigar o que muda.':'Understand the present. Investigate what changes.'}</h1></div><form class="home-search" action="${p('/search.html')}" role="search"><label for="home-query">${pt?'Encontre sua próxima investigação':'Find your next investigation'}</label><div><input id="home-query" name="q" type="search" placeholder="${pt?'Pesquisas, países, temas…':'Research, countries, topics…'}"><button type="submit" aria-label="${pt?'Buscar':'Search'}">↗</button></div></form></section>
    <div class="home-edition container"><span><i aria-hidden="true"></i>${pt?'PESQUISA INDEPENDENTE':'INDEPENDENT RESEARCH'}</span><a href="${p('/research/coverage/')}">${items.length} ${pt?'pesquisas':'publications'} · ${countries.size} ${pt?'países no acervo':'countries in the corpus'}</a><span>${pt?'Última publicação':'Latest publication'} · ${esc(displayDate(lead?.date,locale))}</span></div>
    ${lead?`<section class="home-lead container" aria-labelledby="lead-title"><article class="home-lead-copy"><div class="editorial-meta"><span>${pt?'EM DESTAQUE':'FEATURED RESEARCH'}</span><span>${lead.minutes} min ${pt?'de leitura':'read'}</span></div><a class="lead-program" href="${p(`/research/${lead.program}/`)}">${esc(lead.programLabel)}</a><h2 id="lead-title"><a href="${esc(lead.url)}">${esc(lead.title)}</a></h2><p>${esc(lead.deck)}</p><div class="editorial-actions"><a class="lead-read" href="${esc(lead.url)}">${pt?'Ler pesquisa completa':'Read the research'} <span aria-hidden="true">↗</span></a>${saveButton(lead,locale)}</div></article>${evidence(lead,locale,root)}</section>`:''}
    <section class="home-section container" aria-labelledby="recent-title"><div class="product-section-head"><div><span class="product-kicker">${pt?'PERSPECTIVAS COMPLEMENTARES':'COMPLEMENTARY PERSPECTIVES'}</span><h2 id="recent-title">${pt?'Mais pesquisas, outras conexões':'More research, new connections'}</h2></div><a href="${p('/reports.html')}">${pt?'Ver todo o acervo':'Browse all research'} →</a></div><div class="editorial-grid">${recent.map(x=>researchTile(x,locale)).join('')}</div></section>
    <section class="home-tools" aria-labelledby="tools-title"><div class="container"><div class="product-section-head"><div><span class="product-kicker">${pt?'PARA APROFUNDAR':'GO DEEPER'}</span><h2 id="tools-title">${pt?'Da leitura à investigação':'From reading to investigation'}</h2></div><p>${pt?'Conecte mecanismos, explore estruturas e organize suas hipóteses.':'Connect mechanisms, explore structures and organize your hypotheses.'}</p></div><div class="home-tools-grid">
      <a class="home-tool network-tool" href="${p('/dependencies/')}"><div class="tool-topline"><span>01 / ${pt?'CONEXÕES':'CONNECTIONS'}</span><span aria-hidden="true">↗</span></div>${networkPreview(dependency,locale)}<h3>${pt?'Rede Global de Dependências':'Global Dependency Network'}</h3><p>${pt?'Siga como um choque atravessa recursos, rotas, produção e capital.':'Follow how a shock travels through resources, routes, production and capital.'}</p><span class="tool-foot">${dependency.nodes.length} ${pt?'nós':'nodes'} · ${dependency.edges.length} ${pt?'relações documentadas':'documented relationships'}</span></a>
      <a class="home-tool atlas-tool" href="${p('/opportunities/')}"><div class="tool-topline"><span>02 / ${pt?'ESTRUTURAS':'STRUCTURES'}</span><span aria-hidden="true">↗</span></div><div class="tool-matrix">${states.map((s,i)=>`<div><strong>${atlas.entries.filter(e=>e.state===s).length}</strong><span>${stateLabels[i]}</span></div>`).join('')}</div><h3>${pt?'Atlas de Oportunidades Estruturais':'Structural Opportunity Atlas'}</h3><p>${pt?'Investigue as condições que impedem valor ou ampliam capacidade econômica.':'Investigate the conditions that block value or expand economic capacity.'}</p><span class="tool-foot">${atlas.entries.length} ${pt?'condições ligadas a evidências':'conditions linked to evidence'}</span></a>
      <a class="home-tool notebook-tool" href="${p('/workspace/')}"><div class="tool-topline"><span>03 / ${pt?'SEU CADERNO':'YOUR WORKSPACE'}</span><span aria-hidden="true">↗</span></div><div class="tool-notebook" aria-hidden="true"><span>${pt?'Tese':'Thesis'}</span><span>${pt?'Risco':'Risk'}</span><span>${pt?'O que acompanhar':'What to watch'}</span><i></i><i></i><i></i><i></i><i></i><i></i></div><h3>${pt?'Caderno de pesquisa':'Research workspace'}</h3><p>${pt?'Salve leituras, compare análises e reúna notas e sinais para acompanhar.':'Save reading, compare analyses and collect notes and signals to watch.'}</p><span class="tool-foot">${pt?'Sem cadastro · salvo neste navegador':'No account · saved in this browser'}</span></a>
    </div></div></section>
    <section class="home-section container home-explore" aria-labelledby="explore-title"><div><span class="product-kicker">${pt?'EXPLORE O ACERVO':'EXPLORE THE CORPUS'}</span><h2 id="explore-title">${pt?'Comece por uma pergunta.':'Start with a question.'}</h2><p>${pt?'Cruze temas, países e períodos para encontrar leituras que se complementam.':'Combine topics, countries and dates to find complementary readings.'}</p><a class="product-link" href="${p('/workspace/')}">${pt?'Explorar com filtros':'Explore with filters'} →</a></div><div><h3>${pt?'Temas em pesquisa':'Research topics'}</h3><div class="explore-links">${topics.map(x=>`<a href="${p(`/workspace/?topic=${x.id}`)}">${esc(x.label)}<span>${x.count}</span></a>`).join('')}</div></div><div><h3>${pt?'Países no acervo':'Countries in the corpus'}</h3><div class="explore-links">${places.map(x=>`<a href="${p(`/countries/${x.id}/`)}">${esc(x.label)}<span>${x.count}</span></a>`).join('')}</div></div></section>
    <section class="home-program-section"><div class="container"><div class="product-section-head"><div><span class="product-kicker">${pt?'QUATRO LINHAS, UMA VISÃO CONECTADA':'FOUR PROGRAMS, ONE CONNECTED VIEW'}</span><h2>${pt?'Linhas de pesquisa':'Research programs'}</h2></div><a href="${p('/research/coverage/')}">${pt?'Conhecer a cobertura':'Explore coverage'} →</a></div><div class="home-program-grid">${Object.entries(taxonomy.programs).map(([id,value],i)=>{const covered=items.filter(r=>r.program===id),latest=covered[0];return `<article><div class="editorial-meta"><span>0${i+1}</span><span>${covered.length} ${pt?'pesquisas':'publications'}</span></div><h3><a href="${p(`/research/${id}/`)}">${esc(label(value,locale))}</a></h3>${latest?`<a class="program-latest" href="${esc(latest.url)}"><span>${pt?'LEITURA RECENTE':'RECENT READING'}</span>${esc(latest.title)} ↗</a>`:''}</article>`;}).join('')}</div><a class="home-series" href="${p('/series/energy-materials-industrial-systems/')}"><span class="product-kicker">${pt?'SÉRIE DE PESQUISA':'RESEARCH SERIES'}</span><strong>${esc(label(taxonomy.series['energy-materials-industrial-systems'],locale))}</strong><span aria-hidden="true">↗</span></a></div></section>
    <section class="home-closing container"><div><span class="product-kicker">${pt?'EVIDÊNCIA E INCERTEZA':'EVIDENCE AND UNCERTAINTY'}</span><h2>${pt?'Profundidade exige contexto.':'Depth requires context.'}</h2><p>${pt?'Fontes, mecanismos e limites explícitos. Uma base de pesquisa que se amplia e pode ser revisitada.':'Sources, mechanisms and explicit limits. A growing body of research you can return to.'}</p><a href="${p('/methodology.html')}">${pt?'Conheça o método':'Our research method'} →</a></div><div class="home-follow"><h3>${pt?'Acompanhe novas pesquisas':'Follow new research'}</h3><p>${pt?'Receba as publicações no seu leitor de RSS ou explore o acervo com seu agente.':'Follow publications in your RSS reader or explore the corpus with your agent.'}</p><a href="${p('/feed.xml')}">RSS ↗</a><a href="${p('/mcp-docs/')}">MCP ↗</a></div></section>
  </main>`;
}
